"""empty message

Revision ID: 69424ee1bd2c
Revises: da92a8c2749e
Create Date: 2022-06-07 22:30:27.503337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69424ee1bd2c'
down_revision = 'da92a8c2749e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
